Repository RITlug/teleirc, pull requests merged in 2018-12, with the labels that each got.

#104 Add documentation for missing configs in env.example
  docs/installation.rst
Labels: docs, improvement

#107 Use all system packages for Fedora Docker image
  containers/Dockerfile.fedora
Labels: improvement

#106 Fix and update imgur tests
  tests/TgPhotoHandlerTests.js
  tests/assets/README.md
  tests/assets/test-img-1.jpg
  tests/assets/test-img-2.jpg
  tests/assets/test-img-3.jpg
Labels: improvement, priority:med

#109 Fixed Dockerfiles
  docs/using-docker.rst
  images/Dockerfile.alpine
  images/Dockerfile.fedora
Labels: bug

#110 Add [EDITED] prefix for edited messages on irc.
  config.js
  env.example
  lib/TeleIrc.js
  lib/TelegramHandlers/TgEventListener.js
Labels: new change, priority:med
