Repository RITlug/teleirc, pull requests merged in 2018-10, with the labels that each got.

#65 Nickserv identify
  .env.example
  config.js
  lib/TeleIrc.js
  teleirc.js
  tests/IrcConnectionTests.js
Labels: enhancement, priority:crit

#74 Crash on Telegram bot errors
  package.json
  teleirc.js
Labels: bug, priority:high

#79 Add Fedora CommOps, Diversity, Marketing as users (closes #75)
  docs/who-uses-teleirc.rst
Labels: community, docs

#82 Gitignore change
  .gitignore
Labels: enhancement
