Repository RITlug/teleirc, pull requests merged in 2019-11, with the labels that each got.

#209 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/improvement-to-existing-functionality.md
  .github/ISSUE_TEMPLATE/new-feature-request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: documentation, new change

#203 Build out concurrent Telegram bridge
  cmd/teleirc.go
  env.example
  go.mod
  go.sum
  internal/config.go
  internal/handlers/irc/irc.go
  internal/handlers/telegram/telegram.go
Labels: improvement, needs review

#216 issue templates: Change label 'discussion' -> 'needs triage'
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/improvement-to-existing-functionality.md
  .github/ISSUE_TEMPLATE/new-feature-request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: community, improvement

#215 docs: Support Markdown file type (closes #208)
  docs/Pipfile.lock
  docs/conf.py
Labels: documentation, improvement

#218 ci: Add job to build and test docs
  .travis.yml
  docs/build_docs.sh
Labels: documentation, new change, quality assurance

#222 Fix config parsing
  config.js
Labels: bug
