Repository RITlug/teleirc, pull requests merged in 2019-09, with the labels that each got.

#166 Add MIT License header to source code.
  lib/Helpers.js
  lib/IrcHandlers/IrcActionHandler.js
  lib/IrcHandlers/IrcErrorHandler.js
  lib/IrcHandlers/IrcJoinHandler.js
  lib/IrcHandlers/IrcKickHandler.js
  lib/IrcHandlers/IrcMessageHandler.js
  lib/IrcHandlers/IrcNickServHandler.js
  lib/IrcHandlers/IrcPartHandler.js
  lib/MessageRateLimiter.js
  lib/TeleIrc.js
  lib/TeleIrcErrorCodes.js
  lib/TeleIrcException.js
  lib/TelegramHandlers/TgDocumentHandler.js
  lib/TelegramHandlers/TgErrorHandler.js
  lib/TelegramHandlers/TgEventListener.js
  lib/TelegramHandlers/TgHelpers.js
  lib/TelegramHandlers/TgImgurPhotoHandler.js
  lib/TelegramHandlers/TgJoinHandler.js
  lib/TelegramHandlers/TgMessageHandler.js
  lib/TelegramHandlers/TgPartHandler.js
  lib/TelegramHandlers/TgPhotoHandler.js
  lib/TelegramHandlers/TgStickerHandler.js
  tests/IrcActionHandlerTests.js
  tests/IrcConfigValidationTests.js
  tests/IrcConnectionTests.js
  tests/IrcErrorHandlerTests.js
  tests/IrcJoinHandlerTests.js
  tests/IrcKickHandlerTests.js
  tests/IrcMessageHandlerTests.js
  tests/IrcPartHandlerTests.js
  tests/TelegramToIrcTests.js
  tests/TgDocumentHandlerTests.js
  tests/TgJoinHandlerTests.js
  tests/TgMessageHandlerTests.js
  tests/TgPartHandlerTests.js
  tests/TgPhotoHandlerTests.js
  tests/TgStickerHandlerTests.js
Labels: improvement, needs review

#181 Resolves #174: Build out config parsing
  cmd/teleirc.go
  env.example
  go.mod
  internal/config.go
Labels: new change

#183 Resolves #182: Fix Go module bug introduced in #174
  go.mod
  internal/config.go
Labels: improvement

#187 Add config glossary
  docs/config-file-glossary.rst
Labels: docs

#186 Add support for server password
  config.js
  docs/config-file-glossary.rst
  env.example
  teleirc.js
  tests/IrcConfigValidationTests.js
Labels: new change

#184 Add support for channel key (closes #129).
  config.js
  docs/config-file-glossary.rst
  env.example
  teleirc.js
  tests/IrcConnectionTests.js
Labels: new change

#188 Add base logic connecting IRC and Telegram
  cmd/teleirc.go
  go.mod
  go.sum
  internal/handlers/.gitkeep
  internal/handlers/irc/.gitkeep
  internal/handlers/irc/irc.go
  internal/handlers/telegram/.gitkeep
  internal/handlers/telegram/telegram.go
Labels: new change
