Repository RITlug/teleirc, pull requests merged in 2020-01, with the labels that each got.

#229 docs: Update IRC channel (#ritlug-teleirc -> #rit-lug-teleirc)
  .travis.yml
  README.md
  docs/about/who-uses-teleirc.rst
  docs/dev/contributing.md
  docs/index.rst
Labels: documentation, improvement

#230 Implement handler "interface" and add function for mapping handlers to IRC
  .gitignore
  cmd/teleirc.go
  config.js
  internal/handlers/irc/handlers.go
  internal/handlers/irc/irc.go
  internal/handlers/telegram/telegram.go
  teleirc.js
  tests/IrcConfigValidationTests.js
  tests/IrcConnectionTests.js
Labels: new change

#234 Lay groundwork for unified message handling between IRC <=> Telegram
  internal/config.go
  internal/handlers/telegram/telegram.go
  internal/handlers/telegram/telegram_test.go
Labels: improvement, quality assurance

#232 Implemented IRC joining/parting handlers
  internal/handlers/irc/handlers.go
  internal/handlers/irc/irc.go
Labels: new change
