Repository RITlug/teleirc, pull requests merged in 2020-05, with the labels that each got.

#321 Developer Docs: code conventions
  docs/dev/code-conventions.md
Labels: documentation, improvement

#323 1st Docs Refresh: Structural refactor, add Quick Start Guide
  docs/Pipfile
  docs/Pipfile.lock
  docs/conf.py
  docs/deploy-teleirc.rst
  docs/dev/contributing.md
  docs/index.rst
  docs/quick-install.rst
  docs/user/config-file-glossary.rst
  docs/user/faq.rst
  docs/user/quick-start.md
Labels: documentation, improvement

#322 Add ZWSP between Telegram usernames
  internal/config.go
  internal/handlers/telegram/handler.go
  internal/handlers/telegram/handler_test.go
  internal/handlers/telegram/helpers.go
  internal/handlers/telegram/helpers_test.go
Labels: Telegram, needs changes, new change

#325 docs: Add specific deployment steps (closes #297)
  docs/user/quick-start.md
Labels: T: ops, documentation, improvement, needs review
