Repository RITlug/teleirc, pull requests merged in 2020-02, with the labels that each got.

#235 Allow communication from Telegram => IRC
  cmd/teleirc.go
  internal/config.go
  internal/handlers/telegram/telegram.go
Labels: new change

#239 Initial IRC => Telegram bridging
  cmd/teleirc.go
  internal/handlers/irc/handlers.go
  internal/handlers/irc/irc.go
Labels: IRC, new change

#243 docs: Update girc context in state diagram (closes #233)
  docs/_static/dev/message-state-diagram.png
  docs/_static/dev/message-state-diagram.svg
Labels: documentation, improvement

#250 docs: Update Sphinx dependencies
  docs/Pipfile.lock
Labels: dependencies, documentation, improvement

#251 docs: Add alternate method to get Telegram chat ID (closes #237)
  docs/_static/about/faq-getidsbot.png
  docs/about/faq.rst
  docs/config-file-glossary.rst
Labels: documentation, improvement
