Repository RITlug/teleirc, pull requests merged in 2020-03, with the labels that each got.

#252 docs: Add testing best practices from @Zedjones (closes #236)
  docs/dev/testing.md
Labels: documentation, new change, quality assurance

#261 Resolves #231 (Update IRC Config to contain new field (IRC_CHANNEL_KEY))
  internal/config.go
  internal/handlers/irc/handlers.go
Labels: IRC, improvement, needs review

#254 fmt print statements replaced using the log package
  cmd/teleirc.go
  internal/debug.go
  internal/handlers/irc/irc.go
  internal/handlers/irc/irc_test.go
  internal/handlers/telegram/telegram.go
  internal/handlers/telegram/telegram_test.go
Labels: IRC, Telegram, improvement

#259 Resolves #258 (Small improvements to the error handling for the config)
  internal/config.go
Labels: improvement, quality assurance

#263 ci: Cache Python packages for faster builds
  .travis.yml
Labels: documentation, improvement, quality assurance

#262 ci: Use golangci-lint for Go CI tests (closes #256)
  .travis.yml
Labels: new change, quality assurance

#274 Small changes to the debug file and the logging variables
  cmd/teleirc.go
  internal/debug.go
  internal/handlers/irc/irc.go
  internal/handlers/telegram/telegram.go
Labels: improvement

#273 Create document handler
  internal/handlers/telegram/handler.go
  internal/handlers/telegram/telegram.go
Labels: Telegram, new change

#268 Add timeout to girc connect call
  internal/config.go
  internal/handlers/irc/irc.go
  internal/handlers/telegram/handler.go
Labels: IRC, bug

#276 dependencies: Run `yarn upgrade` before last Node release
  yarn.lock
Labels: bug, dependencies

#283 Sticker handler
  internal/handlers/telegram/handler.go
  internal/handlers/telegram/telegram.go
Labels: Telegram, new change

#284 Added LogDebug
  cmd/teleirc.go
  internal/debug.go
  internal/handlers/irc/handlers.go
  internal/handlers/irc/irc.go
  internal/handlers/telegram/telegram.go
Labels: improvement

#285 Create Telegram update handler
  internal/handlers/telegram/handler.go
  internal/handlers/telegram/telegram.go
Labels: Telegram, new change

#279 docs: Reflect initial v2.x.x changes (closes #278)
  docs/about/who-uses-teleirc.rst
  docs/config-file-glossary.rst
  docs/deploy-teleirc.rst
  docs/dev/contributing.md
  docs/index.rst
  docs/quick-install.rst
  env.example
Labels: documentation, improvement

#281 Create Blacklist Handler (Resolves #247)
  internal/handlers/irc/handlers.go
Labels: IRC, new change

#290 Adding basic LogDebug into the updateHandler
  internal/handlers/telegram/handler.go
Labels: Telegram, improvement

#291 codeclimate: Initial commit (closes #288)
  .codeclimate.yml
  .travis.yml
Labels: new change, quality assurance

#292 ci: Drop Go v1.12.x CI tests
  .travis.yml
Labels: improvement, quality assurance
