Repository RITlug/teleirc, pull requests merged in 2022-10, with the labels that each got.

#403 Strip mIRC formatting
  internal/handlers/irc/handlers.go
Labels: bug, Telegram

#404 Added Location handler
  docs/user/config-file-glossary.rst
  env.example
  internal/config.go
  internal/handlers/telegram/handler.go
  internal/handlers/telegram/handler_test.go
Labels: new change, needs review, Telegram

#405 Build static binary
  build_binary.sh
  docs/user/quick-start.md
Labels: improvement, documentation, needs review
